{% set name = "requests-ecp" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82a0cc4df8435d34e36b5981be6feed6b34205e7501f6e63eb64b2ffae7da663

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=30.3.0
  run:
    - lxml
    - python >=3.5
    - requests
    - requests-kerberos >=0.9.0

test:
  imports:
    - requests_ecp
  requires:
    - pip
    - pytest >=2.9.2
    - requests-mock >=1.5.0
  commands:
    # check dependencies
    - python -m pip check
    # run unit tests
    - python -m pytest -ra --verbose --color yes --pyargs requests_ecp

about:
  home: https://pypi.org/project/requests-ecp/
  dev_url: https://github.com/duncanmmacleod/requests-ecp.git
  doc_url: https://requests-ecp.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: SAML/ECP authentication handler for python-requests
  description: A SAML/ECP authencation handler for python-requests

extra:
  recipe-maintainers:
    - duncanmmacleod
