{% set name = "requests-ecp" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f863c3ba717a7733dbb7662ddbdb8e53a12e971eb6594dc009b7f7bc662befdb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=30.3.0
  run:
    - lxml
    - python >=3.5
    - requests
    - requests-gssapi >=1.2.2

test:
  imports:
    - requests_ecp
  requires:
    - pip
    - pytest >=2.9.2
    - requests-mock >=1.5.0
  commands:
    # check dependencies
    - python -m pip check requests-ecp
    - python -m pip show requests-ecp
    # run unit tests
    - python -m pytest -ra --verbose --color yes --pyargs requests_ecp

about:
  home: https://requests-ecp.readthedocs.io/
  dev_url: https://github.com/duncanmmacleod/requests-ecp.git
  doc_url: https://requests-ecp.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: SAML/ECP authentication handler for python-requests
  description: A SAML/ECP authencation handler for python-requests

extra:
  recipe-maintainers:
    - duncanmmacleod
