{% set name = "requests-ecp" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7f05f6a5cb513391565e8b3d837f443a4f2f51aa731f0d7ad6ae57e1d32d71c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - lxml
    - python >=3.5
    - requests
    - requests-kerberos >=0.9.0

test:
  imports:
    - requests_ecp
  requires:
    - pytest
    - requests-mock
  source_files:
    - test_requests_ecp.py
  commands:
    - python -m pytest test_requests_ecp.py

about:
  home: https://pypi.org/project/requests-ecp/
  dev_url: https://github.com/duncanmmacleod/requests-ecp/
  doc_url: https://requests-ecp.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: SAML/ECP authentication handler for python-requests
  description: A SAML/ECP authencation handler for python-requests

extra:
  recipe-maintainers:
    - duncanmmacleod
